name: flutsplash
description: Unsplash Client written in Flutter.
publish_to: "none"
version: 2.0.0+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  dio: ^4.0.0
  flutter_inappwebview: ^5.3.2
  flutter_staggered_grid_view: ^0.4.0
  fluttertoast: ^8.0.4
  font_awesome_flutter: ^9.0.0
  freezed_annotation: ^0.14.2
  future_progress_dialog: ^0.2.0
  get: ^4.1.3
  google_fonts: ^2.0.0
  open_file: ^3.1.0
  package_info: ^2.0.0
  path_provider: ^2.0.1
  pedantic: ^1.11.0
  permission_handler: ^6.1.1
  share: ^2.0.1
  shimmer: ^2.0.0-nullsafety.0
  sn_progress_dialog: ^1.0.0-nullsafety.0
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  freezed: ^0.14.2
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true
  assets:
    - images/header.png
