name: flutsplash
description: Unsplash Client written in Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  google_fonts: ^2.0.0
  flutter_dotenv: ^4.0.0-nullsafety.0
  flutter_staggered_grid_view: 0.4.0-nullsafety.3
  get: ^4.1.3
  url_launcher: ^6.0.3
  freezed_annotation:
  flutter:
    sdk: flutter

dev_dependencies:
  json_serializable:
  build_runner:
  freezed:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env